In [ ]:
"""

Abbiamo una lista di liste: 
mat = [[0, 1, 2, 3, 4], 
[5, 6, 7, 8, 9], 
[10, 11, 12, 13, 14]] 

Che tipo di struttura dati o matematica potrebbe rappresentare? 
Notare che tutte le liste "interne" sono della stessa dimensione 
Come facciamo per accedere ad un elemento in particolare?

np.array di cinque colonne e tre righe

"""

In [1]:
import numpy as np
import pandas as pd
import math

In [4]:
mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]

In [5]:
mat_array = np.array(mat)

In [6]:
mat_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
mat_array.shape

(3, 5)

In [10]:
mat_array[0,:]

array([0, 1, 2, 3, 4])

In [12]:
mat_array[-2,:]

array([5, 6, 7, 8, 9])

In [43]:
mat_array[1,0::2] # seconda riga con step di 2

array([5, 7, 9])

In [13]:
mat_array[1,2]

7

In [ ]:
"""

Importiamo il modulo math e proviamo a usare le funzioni .sin() .cos() .factorial() e la variabile .pi la riconoscete?

In [26]:
x = math.sin(math.pi/2)

In [27]:
x

1.0

In [28]:
y = math.cos(math.pi/2)

In [29]:
y

6.123233995736766e-17

In [23]:
z = math.factorial(15)

In [24]:
z

1307674368000

In [30]:
a = math.degrees(math.pi)

In [31]:
a

180.0

In [ ]:
"""
L'azienda Object SpA ha creato una lista di quanti oggetti ha venduto ogni mese nell'ultimo anno: 
lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350] 
trasformiamola in un array NumPy (casting): 
lst = np.array(lst)
e rispondiamo alle domande del CEO della Object SpA: 
1 qual è stata la vendita massima mensile? E quella minima? 
2 quali sono le vendite mensili maggiori di 4999 oggetti? E quante ne sono? 
3 quali sono le vendite minori di 3000 oggetti?
4 in media quanti oggetti sono stati venduti al mese?
"""

In [32]:
lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]

In [33]:
lst_nparray = np.array(lst)

In [34]:
lst_nparray

array([2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100,
       5350])

In [35]:
print(lst_nparray.max())  #1 vendita massima mensile

8150


In [36]:
print(lst_nparray.min())  #1 vendita minima mensile

1280


In [45]:
lst_nparray_filter = lst_nparray > 4999 # 2 quali sono le vendite mensili maggiori di 4999 oggetti? E quante ne sono? 
filter = lst_nparray[lst_nparray_filter]
print(filter)
len(filter)

[5500 7200 6410 8150 7100 5350]


6

In [40]:
lst_nparray[lst_nparray>4999]

array([5500, 7200, 6410, 8150, 7100, 5350])

In [46]:
lst_nparray_filter_min = lst_nparray < 3000 # 3 quali sono le vendite minori di 3000 oggetti?
filter_min = lst_nparray[lst_nparray_filter_min]
print(filter_min)
len(filter_min)

[2000 1280 1900 2500]


4

In [44]:
print(lst_nparray.mean()) #4 in media quanti oggetti sono stati venduti al mese?

4634.166666666667


In [50]:
print(round(lst_nparray.mean(),2)) # arrotodnamento a 2 decimali

4634.17


In [ ]:
"""
Esercizio Consideriamo il seguente dizionario: 
fatturati_dict = {1997: 12_000, 1998: 15_000, 1999: 20_000, 2000: 23_000, 2001: 25_000, 2002: 17_000, 2003: 14_000, 2004: 21_000} 
Consideriamo ora la seguente Series: 
fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000], 
index=range(1997, 2005)) 
Possiamo accedere alle stesse informazioni nello stesso modo: fatturati_dict[1997] fatturati_series[1997] 
Dunque qual è la differenza tra i due tipi di dato? Cosa potremmo fare con la Series che non possiamo fare con il dizionario?
"""

In [51]:
fatturati_dict = {1997: 12_000, 1998: 15_000, 1999: 20_000, 2000: 23_000, 2001: 25_000, 2002: 17_000, 2003: 14_000, 2004: 21_000}

In [52]:
print(fatturati_dict)

{1997: 12000, 1998: 15000, 1999: 20000, 2000: 23000, 2001: 25000, 2002: 17000, 2003: 14000, 2004: 21000}


In [53]:
fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000], index=range(1997, 2005)) 

In [54]:
print(fatturati_series)

1997    12000
1998    15000
1999    20000
2000    23000
2001    25000
2002    17000
2003    14000
2004    21000
dtype: int64


In [ ]:
"""
dizionario struttura base dati python -> dati memorizzati con tipologia chiave valore. si riperiscono i dati in maniera diretta (chiav
pandas -> gestione virtualizzata. libreria esternerna specializzata in series (monodimensione) e dataframe (+ dimensioni)
series: ci falicita le operazioni medie max ecc cosa che non possiamo fare su dizionario
"""

In [ ]:
"""
Esercizio L'azienda Object SpA ha un dataset con tutti gli stipendi dei dipendenti, memorizzato in un ndarray: 
import numpy as np 
stipendi = np.array( [100, 200, 300, 400, 500,  600, 700, 800, 900, 1000] ) 
L'azienda ci chiede di raddoppiare tutti gli stipendi; facciamolo in due modi: 
• con un ciclo for
• con il masking

In [63]:
stipendi = [100, 200, 300, 400, 500,  600, 700, 800, 900, 1000]
for stipendio in stipendi:
    print(stipendio*2)
    

200
400
600
800
1000
1200
1400
1600
1800
2000


In [66]:
stipendi = [100, 200, 300, 400, 500,  600, 700, 800, 900, 1000]
lista_stipendi_raddopiati = []
for stipendio in stipendi:
    lista_stipendi_raddopiati.append(stipendio*2)

print(lista_stipendi_raddopiati)

[200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]


In [62]:
stipendi_array = np.array(stipendi)
stipendi_array*2

array([ 200,  400,  600,  800, 1000, 1200, 1400, 1600, 1800, 2000])

In [72]:
libri =["enciclopedia","atlante","dizionario","enciclopedia"]

for libro in libri:
    print(libro)

enciclopedia
atlante
dizionario
enciclopedia


In [73]:
for contatore, libro in enumerate(libri):
    print(contatore, libro)

0 enciclopedia
1 atlante
2 dizionario
3 enciclopedia


In [74]:
nomi = ["Anna","Bruno","Carla"]
eta = [28,34,29]
for nome, eta in zip(nomi, eta):                 
    print(f"{nome} ha {eta} anni")         #f string, si usa molto

Anna ha 28 anni
Bruno ha 34 anni
Carla ha 29 anni
